### ISSUE TITLE
Continued test failures on nightly_linux_extra_rmw_release

### ISSUE THREAD

**Issue by mjcarroll** [ros2/build_farmer#150] opened 2018-10-31 13:31 UTC
It appears that a few of the tests related to `DynamicArrayStaticArrayPrimitivesNested` are continuing to fail on the `nightly_linux_extra_rmw_release` builds.

https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/152/

@jacobperron I believe you resolved this elsewhere, can you take a look?

**Comment by jacobperron** [comment] 2018-10-31 18:30
Looks like an issue building with FastRTPS with dynamic type support and OpenSplice (which were not run as part of the original CI job for ros2/system_tests#302).

CI for master (up to `test_communication`) using FastRTPS dynamic and OpenSplice:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5427)](http://ci.ros2.org/job/ci_linux/5427/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2134)](http://ci.ros2.org/job/ci_linux-aarch64/2134/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4501)](http://ci.ros2.org/job/ci_osx/4501/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5368)](http://ci.ros2.org/job/ci_windows/5368/)

**Comment by jacobperron** [comment] 2018-10-31 18:32
Actually, based on the failing tests, it looks like FastRTPS with dynamic type support and rclcpp is the common denominator.

**Comment by jacobperron** [comment] 2018-11-06 23:17
I am not able to reproduce locally.

**Comment by clalancette** [comment] 2018-12-07 14:18
The original issue here looks like it is solved; at least, last night's build was green: https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/189/ .  I'm going to close this for now, but we can reopen if it isn't truly fixed (or I'm missing something).

**Closed as completed by clalancette** 2018-12-07 14:18 UTC

**Comment by jacobperron** [comment] 2018-12-07 17:58
Sounds like it was fixed: https://github.com/ros2/rmw_fastrtps/pull/233#issuecomment-442117942
