### ISSUE TITLE
nightly_win_rep has some known flakey tests

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#37] opened 2017-06-21 14:07 UTC
There were a few new issues in the Windows build, and some that went away.  New issues:

- projectroot.test_wait__rmw_connext_cpp
- projectroot.test_wait__rmw_fastrtps_cpp
- WaitSetTestFixture__rmw_fastrtps_cpp.finite_timeout
- WaitSetTestFixture__rmw_connext_cpp.zero_timeout

**Comment by mikaelarguedas** [comment] 2017-06-21 14:36
these are known to be flaky so they are not new failure due to recent changes

**Comment by clalancette** [comment] 2017-06-21 14:38
Good, thanks for letting me know.  I'm actually going to change the title of this to track the flakey tests for the future.

**Comment by mikaelarguedas** [comment] 2017-06-21 14:45
I don't think that manually creating and updating issues tracking flaky tests is the most efficient solution. @dhood wrote somr scripts to compare test failures over time. I think we should automate that but that will be after the beta. In the meantime it would be good to focus on actual regressions for the beta rather than opening an issue for each non green job IMO

**Comment by clalancette** [comment] 2017-06-21 14:47
The problem is that right now this is just "tribal knowledge"; I had no way of knowing that these are known flakey tests.  Having some place to track them is worthwhile, I think.

**Comment by dirk-thomas** [comment] 2017-06-21 15:32
> The problem is that right now this is just "tribal knowledge"; I had no way of knowing that these are known flakey tests.

The first indicator is the age of a failing test is the `age`. If it is `1` the test didn't fail in the last run. And if you browse through a few of the previous builds the same test will show up sometimes.

> I don't think that manually creating and updating issues tracking flaky tests is the most efficient solution.

:+1:

**Comment by mikaelarguedas** [comment] 2017-07-21 17:40
closing this in favor of #41

**Closed as completed by mikaelarguedas** 2017-07-21 17:40 UTC
