### ISSUE TITLE
rtiddsgen sometimes crashes with IO Error when building in parallel on linux

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#47] opened 2017-08-28 21:32 UTC
```
ERROR com.rti.ndds.nddsgen.Main I/O error generating code
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at com.rti.ndds.nddsgen.CodeGeneratorServer.<init>(Unknown Source)
	at com.rti.ndds.nddsgen.Main.main(Unknown Source)
```

**Comment by dirk-thomas** [comment] 2017-08-28 21:37
Please consider reporting this to RTI together with a reproducible example if that is still a problem in Connext 5.3.

**Comment by dirk-thomas** [comment] 2018-01-04 00:07
I will close this for now since we have migrated to Connext 5.3 since then. If it happens again this can be reopened.

**Closed as completed by dirk-thomas** 2018-01-04 00:07 UTC
