### ISSUE TITLE
Talker/Listener output test failed despite having correct output

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#49] opened 2017-09-07 17:21 UTC
Possibly a bug belonging on https://github.com/ros2/launch . Making ticket here because I can't investigate it fully right now.

**Job**

http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/772/
linux_slave_on_master

**Test**

projectroot.test_tutorial_talker_listener__rmw_fastrtps_cpp
demo_nodes_cpp.test_tutorial_talker_listener__rmw_fastrtps_cpp.xunit.missing_result

The tests use `launch_testing` to check that the output matches expectations.

Listener regex: `I heard: \[Hello World: \d+\]`
Talker text: `Publishing: 'Hello World: 1'`

**Test output**

```
      Start 16: test_tutorial_talker_listener__rmw_fastrtps_cpp

16: Test command: /home/rosbuild/ci_scripts/venv/bin/python3 "-u" "/home/rosbuild/ci_scripts/ws/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/rosbuild/ci_scripts/ws/build/demo_nodes_cpp/test_results/demo_nodes_cpp/test_tutorial_talker_listener__rmw_fastrtps_cpp.xunit.xml" "--output-file" "/home/rosbuild/ci_scripts/ws/build/demo_nodes_cpp/ament_cmake_nose/test_tutorial_talker_listener__rmw_fastrtps_cpp.txt" "--env" "RCL_ASSERT_RMW_ID_MATCHES=rmw_fastrtps_cpp" "RMW_IMPLEMENTATION=rmw_fastrtps_cpp" "--command" "/home/rosbuild/ci_scripts/venv/bin/python3" "-u" "/usr/bin/nosetests3" "/home/rosbuild/ci_scripts/ws/build/demo_nodes_cpp/test_talker_listener__rmw_fastrtps_cpp_.py" "--nocapture" "--with-xunit" "--xunit-file=/home/rosbuild/ci_scripts/ws/build/demo_nodes_cpp/test_results/demo_nodes_cpp/test_tutorial_talker_listener__rmw_fastrtps_cpp.xunit.xml" "--xunit-testsuite-name=demo_nodes_cpp.nosetests"
16: Test timeout computed to be: 30
16: -- run_test.py: extra environment variables:
16:  - RCL_ASSERT_RMW_ID_MATCHES=rmw_fastrtps_cpp
16:  - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
16: -- run_test.py: invoking following command in '/home/rosbuild/ci_scripts/ws/src/ros2/demos/demo_nodes_cpp':
16:  - /home/rosbuild/ci_scripts/venv/bin/python3 -u /usr/bin/nosetests3 /home/rosbuild/ci_scripts/ws/build/demo_nodes_cpp/test_talker_listener__rmw_fastrtps_cpp_.py --nocapture --with-xunit --xunit-file=/home/rosbuild/ci_scripts/ws/build/demo_nodes_cpp/test_results/demo_nodes_cpp/test_tutorial_talker_listener__rmw_fastrtps_cpp.xunit.xml --xunit-testsuite-name=demo_nodes_cpp.nosetests
16: (test_executable_0) pid 2824: ['/home/rosbuild/ci_scripts/ws/build/demo_nodes_cpp/talker'] (all > console, InMemoryHandler: test_executable_0)
16: (test_executable_1) pid 2825: ['/home/rosbuild/ci_scripts/ws/build/demo_nodes_cpp/listener'] (all > console, InMemoryHandler: test_executable_1)
16: [test_executable_0] Publishing: 'Hello World: 1'
16: [test_executable_0] Publishing: 'Hello World: 2'
16: [test_executable_0] Publishing: 'Hello World: 3'
16: [test_executable_0] Publishing: 'Hello World: 4'
16: [test_executable_0] Publishing: 'Hello World: 5'
16: [test_executable_0] Publishing: 'Hello World: 6'
16: [test_executable_0] Publishing: 'Hello World: 7'
16: [test_executable_1] I heard: [Hello World: 2]
16: [test_executable_1] I heard: [Hello World: 3]
16: [test_executable_1] I heard: [Hello World: 4]
16: [test_executable_1] I heard: [Hello World: 5]
16: [test_executable_1] I heard: [Hello World: 6]
16: [test_executable_1] I heard: [Hello World: 7]
16: [test_executable_0] Publishing: 'Hello World: 8'
16: [test_executable_0] Publishing: 'Hello World: 9'
16: [test_executable_0] Publishing: 'Hello World: 10'
16: [test_executable_0] Publishing: 'Hello World: 11'
16: [test_executable_0] Publishing: 'Hello World: 12'
16: [test_executable_0] Publishing: 'Hello World: 13'
16: [test_executable_0] Publishing: 'Hello World: 14'
16: [test_executable_0] Publishing: 'Hello World: 15'
16: [test_executable_0] Publishing: 'Hello World: 16'
16: [test_executable_0] Publishing: 'Hello World: 17'
16: [test_executable_0] Publishing: 'Hello World: 18'
16: [test_executable_0] Publishing: 'Hello World: 19'
16: [test_executable_0] Publishing: 'Hello World: 20'
16: [test_executable_0] Publishing: 'Hello World: 21'
16: [test_executable_0] Publishing: 'Hello World: 22'
16: [test_executable_0] Publishing: 'Hello World: 23'
16: [test_executable_0] Publishing: 'Hello World: 24'
16: [test_executable_0] Publishing: 'Hello World: 25'
16: [test_executable_0] Publishing: 'Hello World: 26'
16: [test_executable_0] Publishing: 'Hello World: 27'
16: [test_executable_0] Publishing: 'Hello World: 28'
16: [test_executable_0] Publishing: 'Hello World: 29'
16: [test_executable_0] Publishing: 'Hello World: 30'
16: [test_executable_0] Publishing: 'Hello World: 31'
16: [test_executable_0] Publishing: 'Hello World: 32'
16: [test_executable_0] Publishing: 'Hello World: 33'
16: [test_executable_0] Publishing: 'Hello World: 34'
16: [test_executable_0] Publishing: 'Hello World: 35'
16: [test_executable_0] Publishing: 'Hello World: 36'
16: [test_executable_0] Publishing: 'Hello World: 37'
16: [test_executable_0] Publishing: 'Hello World: 38'
16: [test_executable_0] Publishing: 'Hello World: 39'
16: [test_executable_0] Publishing: 'Hello World: 40'
16: [test_executable_0] Publishing: 'Hello World: 41'
16: [test_executable_0] Publishing: 'Hello World: 42'
16: [test_executable_0] Publishing: 'Hello World: 43'
16: [test_executable_0] Publishing: 'Hello World: 44'
16: [test_executable_0] Publishing: 'Hello World: 45'
16: [test_executable_0] Publishing: 'Hello World: 46'
16: [test_executable_0] Publishing: 'Hello World: 47'
16: [test_executable_0] Publishing: 'Hello World: 48'
16: [test_executable_0] Publishing: 'Hello World: 49'
16: [test_executable_0] Publishing: 'Hello World: 50'
16: [test_executable_0] Publishing: 'Hello World: 51'
16: [test_executable_0] Publishing: 'Hello World: 52'
16: [test_executable_0] Publishing: 'Hello World: 53'
16: [test_executable_0] Publishing: 'Hello World: 54'
16: [test_executable_0] Publishing: 'Hello World: 55'
16: [test_executable_0] Publishing: 'Hello World: 56'
16: [test_executable_0] Publishing: 'Hello World: 57'
16: [test_executable_0] Publishing: 'Hello World: 58'
16: [test_executable_0] Publishing: 'Hello World: 59'
16/18 Test #16: test_tutorial_talker_listener__rmw_fastrtps_cpp .................................***Timeout  30.01 sec
```

The test output shows the subscriber only receives messages for a short period of time, however the test does have the required output in the console. I would expect the test to have been marked as passed.

**Comment by nuclearsandwich** [comment] 2018-02-22 19:39
@sloretz did you ever have time to follow up on this one?

Is it possible that this is related to https://github.com/ros2/build_cop/issues/80#issuecomment-356783264 ?

**Comment by sloretz** [comment] 2018-02-23 20:56
@nuclearsandwich I didn't follow up on it. It is possible. I don't see it in the most recent repeated linux nightly, so maybe this can be closed.

**Comment by nuclearsandwich** [comment] 2018-02-23 21:16
It's unclear if the test, test harness, or code under test is buggy or if this test is just flaky (cc #41). Since it's not easy to reproduce on command I agree that we can close it for now.

**Closed as completed by nuclearsandwich** 2018-02-23 21:16 UTC
Labels: help wanted
