### ISSUE TITLE
test_action_client_server__rclcpp__rclpy__rmw_fastrtps_cpp fails on Windows CI

### ISSUE THREAD

**Issue by hidmic** [ros2/build_farmer#225] opened 2019-08-08 17:12 UTC
Curious thing is that it fails on default CI builds e.g. https://ci.ros2.org/job/ci_windows/7660/, but not for release builds e.g. https://ci.ros2.org/job/ci_windows/7685/. This is not specific to the branch, as it also shows in https://ci.ros2.org/job/ci_windows/7661. 

I've so far failed to reproduce on a Windows Server VM.

**Comment by sloretz** [comment] 2019-08-08 21:21
I heard this might have something to do with `CMAKE_BUILD_TYPE=None`, but even with that I'm unable to reproduce on the Windows CI machine `portable`

1. Into `C:\J\workspace\ci_windows\ws` I checked out `ros2.repos` from `master` and used `vcs` to clone the repos.

1.
    ```
    colcon build --merge-install --build-base "build_None" --install-base "install_None" --packages-up-to test_communication --cmake-args -DCMAKE_BUILD_TYPE=None -DBUILD_TESTING=ON -DINSTALL_EXAMPLES=OFF -DSECURITY=ON
    ```

1.
    ```
    colcon test --event-handlers console_direct+ --merge-install --build-base "build_None" --install-base "install_None" --packages-select test_communication --ctest-args -R test_action_client_server__rclcpp__rclpy__rmw_fastrtps_cpp$
    ```

**Comment by sloretz** [comment] 2019-08-08 21:50
@hidmic I can't reproduce this on `portable` or on `windshield` using the master branches [![Build Status](https://ci.ros2.org/job/ci_windows/7703/badge/icon)](https://ci.ros2.org/job/ci_windows/7703/)

```
14:47:52 The following tests passed:
14:47:52 	test_action_client_server__rclpy__rmw_connext_cpp
14:47:52 	test_action_client_server__rclpy__rclcpp__rmw_connext_cpp
14:47:52 	test_action_client_server__rclcpp__rclpy__rmw_connext_cpp
14:47:52 	test_action_client_server__rclcpp__rmw_connext_cpp
14:47:52 	test_action_client_server__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp
14:47:52 	test_action_client_server__rclpy__rclcpp__rmw_connext_cpp__rmw_fastrtps_cpp
14:47:52 	test_action_client_server__rclcpp__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp
14:47:52 	test_action_client_server__rclcpp__rmw_connext_cpp__rmw_fastrtps_cpp
14:47:52 	test_action_client_server__rclpy__rmw_fastrtps_cpp__rmw_connext_cpp
14:47:52 	test_action_client_server__rclpy__rclcpp__rmw_fastrtps_cpp__rmw_connext_cpp
14:47:52 	test_action_client_server__rclcpp__rclpy__rmw_fastrtps_cpp__rmw_connext_cpp
14:47:52 	test_action_client_server__rclcpp__rmw_fastrtps_cpp__rmw_connext_cpp
14:47:52 	test_action_client_server__rclpy__rmw_fastrtps_cpp
14:47:52 	test_action_client_server__rclpy__rclcpp__rmw_fastrtps_cpp
14:47:52 	test_action_client_server__rclcpp__rclpy__rmw_fastrtps_cpp
14:47:52 	test_action_client_server__rclcpp__rmw_fastrtps_cpp
14:47:52 
14:47:52 100% tests passed, 0 tests failed out of 16
```

Is it possible those PRs have some repo in common that needs a rebase on master?

**Comment by hidmic** [comment] 2019-08-08 22:15
Not that I know of, but I'll rebase the one that's still open and try again.

**Comment by hidmic** [comment] 2019-08-12 17:18
@sloretz I ran CI on the same branch with no apparent changes and it turned out:

 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7719)](http://ci.ros2.org/job/ci_windows/7719/) 

so I'm at loss here too. A flake?

**Comment by sloretz** [comment] 2019-08-12 17:31
> A flake?

Maybe another machine on the network used the same ROS_DOMAIN_ID and had the same action server running? I think this could be closed as an unexplained but temporary issue.

**Comment by sloretz** [comment] 2020-04-20 18:42
I'll close this since it's been a while without being able to reproduce it, and the test passed on last night's `nightly_win_rep` job: https://ci.ros2.org/view/nightly/job/nightly_win_rep/1824/testReport/(root)/projectroot/test_action_client_server__rclcpp__rclpy__rmw_fastrtps_cpp/

**Closed as completed by sloretz** 2020-04-20 18:42 UTC
