### ISSUE TITLE
ARM jobs hanging

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#72] opened 2017-12-02 17:36 UTC
Some jobs don't finish after disconnecting the ssh agend and just hang forever:
http://ci.ros2.org/job/ci_linux-aarch64/848/console
http://ci.ros2.org/job/ci_linux-aarch64/850/console

I haven't seen it before so maybe its just a fluke.
@nuclearsandwich is that something you noticed in the past ?

Around the same time we had a job hanging in the middle of a build for no apparent reason:
http://ci.ros2.org/job/ci_linux-aarch64/847/console

**Comment by mikaelarguedas** [comment] 2017-12-02 19:33
Not a fluke, jobs this morning also all hang in the same spot 
http://ci.ros2.org/job/nightly_turtlebot-demo_linux-aarch64_release/146
http://ci.ros2.org/job/nightly_linux-aarch64_release/248/

**Comment by nuclearsandwich** [comment] 2017-12-02 21:51
This is a new failure mode to me as well.

**Comment by nuclearsandwich** [comment] 2017-12-02 23:58
Okay I dumped a bunch of info in Slack. There was an old cmake process on the host that was in unkillable sleep and whenever process enumeration would hit it it would hang. The Jenkins agent logic for cleaning up SSH agents was enumerating the process space to do so and getting stuck. I tried to to grab as much info I could about the stuck process before rebooting. It took two tries in the Packet.net console to get the system to reboot successfully but in the end it did. A test arm job http://ci.ros2.org/job/test_ci_linux-aarch64/1/console is running now but I'm going to ~~~tempt fate~~~ be optimistic and close this issue now.

**Comment by dhood** [comment] 2017-12-14 23:54
happened again last night. These jobs hung:
http://ci.ros2.org/job/nightly_linux-aarch64_repeated/266/
http://ci.ros2.org/job/nightly_linux-aarch64_release/261/
http://ci.ros2.org/job/nightly_turtlebot-demo_linux-aarch64_release/160/
http://ci.ros2.org/job/nightly_linux-aarch64_debug/301/

I killed them with the x in the UI but @mikaelarguedas just told me that's probably not sufficient

**Comment by mikaelarguedas** [comment] 2017-12-15 00:40
Yeah I went in and same problem as before, rogue zombie process preventing `ps ax` to complete. I didnt see cmake in the list, the only process that seemed to be sleeping for a while was dockerd. I rebooted the machine a few times and it seems to be back in a good state. Hopefully the [next jobs](http://ci.ros2.org/job/ci_linux-aarch64/928/) won't hang

**Comment by dhood** [comment] 2017-12-15 00:46
Thanks, I should have known there was something more sinister at work if there were so many hanging at once.. was optimistic of me to think new jobs would work from just cancelling the hanging ones (I only found this ticket afterwards, while you were already investigating). I won't cancel them again in this sort of situation: appreciate you looking into it the right way

**Comment by nuclearsandwich** [comment] 2017-12-15 13:47
> I didnt see cmake in the list, the only process that seemed to be sleeping for a while was dockerd

So the thing about this particular failure mode is that the hung process itself won't be listed as trying to introspect that process is what causes the hang.

The way I traced it back to that cmake process was by listing all processes with `ps aux`, noting the pid of the last process that did print, then finding the subsequent process in `/proc` and gathering info about it via procfs. Some info like the exact procline was also inaccessible as it would hang when manually inspecting in proc. I did capture some info which is stored in root's home directory.

Since this is now a recurring issue, we should probably figure out how to trace it and if possible, how to prevent it from hanging builds until we can kick it over.

**Comment by mikaelarguedas** [comment] 2018-01-03 16:17
Reopening as this  is still an issue and will need to be investigated in the near future

**Comment by nuclearsandwich** [comment] 2018-02-15 00:55
Have we seen this again since Jan 3?

**Comment by dirk-thomas** [comment] 2018-02-15 03:20
I haven't during my shift in January.

**Comment by nuclearsandwich** [comment] 2018-02-15 22:29
I'd nominate closing this for now then. It _is_ a confirmed issue but not one we can reproduce reliably enough to investigate and mitigation steps (reboot the machine via packet UI) are documented above.

**Closed as completed** 2018-02-22 19:06 UTC
