### ISSUE TITLE
Nightly windows build failed to remove colcon

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#185] opened 2019-04-23 16:05 UTC
Early on in the setup for the tooling for the nightly windows jobs, they try to remove the old packages using a `pip uninstall`.  This fails sometimes, as in https://ci.ros2.org/view/nightly/job/nightly_win_deb/1229/console:

```

11:50:19 ==> "C:\Python37\python_d.exe" -m pip uninstall -y colcon-core colcon-defaults colcon-library-path colcon-metadata colcon-mixin colcon-output colcon-package-information colcon-package-selection colcon-parallel-executor colcon-powershell colcon-python-setup-py colcon-recursive-crawl colcon-test-result colcon-cmake colcon-ros
11:50:20 C:\Python37\lib\site-packages\pip\_vendor\html5lib\_trie\_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
11:50:20   from collections import Mapping
11:50:20 Uninstalling colcon-core-0.3.20:
11:50:20   Successfully uninstalled colcon-core-0.3.20
11:50:23 Exception:
11:50:23 Traceback (most recent call last):
11:50:23   File "C:\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
11:50:23     os.unlink(fullname)
11:50:23 PermissionError: [WinError 5] Access is denied: 'C:\\WINDOWS\\TEMP\\pip-uninstall-u9q4shen\\colcon.exe'
11:50:23 
11:50:23 During handling of the above exception, another exception occurred:
11:50:23 
11:50:23 Traceback (most recent call last):
11:50:23   File "C:\Python37\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
11:50:23     status = self.run(options, args)
11:50:23   File "C:\Python37\lib\site-packages\pip\_internal\commands\uninstall.py", line 78, in run
11:50:23     uninstall_pathset.commit()
11:50:23   File "C:\Python37\lib\site-packages\pip\_internal\req\req_uninstall.py", line 412, in commit
11:50:23     self._moved_paths.commit()
11:50:23   File "C:\Python37\lib\site-packages\pip\_internal\req\req_uninstall.py", line 263, in commit
11:50:23     save_dir.cleanup()
11:50:23   File "C:\Python37\lib\site-packages\pip\_internal\utils\temp_dir.py", line 83, in cleanup
11:50:23     rmtree(self.path)
11:50:23   File "C:\Python37\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
11:50:23     return Retrying(*dargs, **dkw).call(f, *args, **kw)
11:50:23   File "C:\Python37\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
11:50:23     raise attempt.get()
11:50:23   File "C:\Python37\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
11:50:23     six.reraise(self.value[0], self.value[1], self.value[2])
11:50:23   File "C:\Python37\lib\site-packages\pip\_vendor\six.py", line 693, in reraise
11:50:23     raise value
11:50:23   File "C:\Python37\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
11:50:23     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
11:50:23   File "C:\Python37\lib\site-packages\pip\_internal\utils\misc.py", line 121, in rmtree
11:50:23     onerror=rmtree_errorhandler)
11:50:23   File "C:\Python37\lib\shutil.py", line 513, in rmtree
11:50:23     return _rmtree_unsafe(path, onerror)
11:50:23   File "C:\Python37\lib\shutil.py", line 397, in _rmtree_unsafe
11:50:23     onerror(os.unlink, fullname, sys.exc_info())
11:50:23   File "C:\Python37\lib\site-packages\pip\_internal\utils\misc.py", line 133, in rmtree_errorhandler
11:50:23     func(path)
11:50:23 PermissionError: [WinError 5] Access is denied: 'C:\\WINDOWS\\TEMP\\pip-uninstall-u9q4shen\\colcon.exe'
```

It says that it is a "Permission Error", but it is unclear on whether it is truly a permission problem or if it happens to be in-use so is not allowed to be removed.

**Comment by dirk-thomas** [comment] 2019-04-23 16:06
Duplicate of #161.

**Closed as completed by dirk-thomas** 2019-04-23 16:06 UTC
Labels: duplicate
