### ISSUE TITLE
Eci failures with FastRTPS

### ISSUE THREAD

**Issue by mjcarroll** [ros2/build_farmer#270] opened 2020-04-06 22:15 UTC
Recently Eloquent builds with FastRTPS have been failing.

http://build.ros2.org/view/Eci/job/Eci__nightly-fastrtps-dynamic_ubuntu_bionic_amd64/

**Comment by cottsay** [comment] 2020-04-07 05:58
I worked through showing that the following weren't the cause of the regression:
* Changes to any repositories in `ros2.repos`
* Changes to `ros_buildfarm`
* A new base image for `ubuntu:bionic`

The Jenkins logs were sufficient to demonstrate their innocence.

I was convinced that the problem was an update to the Bionic system packages, but after disabling updates and security repos, I was seeing the same error and getting less confident. We should probably find a way to make this more clear for future comparisons - maybe dumping the apt log to console or something.

After thinking through this critically, I decided to give a close look to vendor packages, and that's where I found the problem.

`foonathan_memory_vendor` [is cloning from master](https://github.com/eProsima/foonathan_memory_vendor/blob/ebf1fe58949148afd4352fbaddd9cf8d22b9e5a9/CMakeLists.txt#L57-L59). I recommend that we target a specific ref in all released ROS 2 distros right away - a push to the `foonathan/memory` repository could break source builds at any time.

[Here is a change](https://github.com/foonathan/memory/commit/293f88d3a7cc49b25ffd4e9f27b1e4a8e14ee0d7) to foonathan that we unknowingly took, which I believe is causing the break.

**Comment by mjcarroll** [comment] 2020-04-07 14:58
Well hey, thanks for digging into this @cottsay, I really appreciate it.  I'll try a run with `foonathan` pinned back to see if that makes a difference.

**Comment by clalancette** [comment] 2021-02-03 20:33
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.

**Closed as completed by clalancette** 2021-02-03 20:33 UTC
Labels: bug, in progress
