### ISSUE TITLE
New GCC warnings on Linux

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#64] opened 2017-10-25 15:34 UTC
Beginning with [nightly_turtlebot-demo #100](http://ci.ros2.org/view/nightly/job/nightly_turtlebot-demo_linux_release/100/warnings22Result/) and [nightly_linux #603](http://ci.ros2.org/job/nightly_linux_release/603/warnings22Result/) GCC warnings have appeared. The initial builds list a bunch of `Warning:unused-variable` but starting with [nightly_turtlebot-demo #102](http://ci.ros2.org/view/nightly/job/nightly_turtlebot-demo_linux_release/102/warnings22Result/) and [nightly_linux #605](http://ci.ros2.org/job/nightly_linux_release/605/warnings22Result/) a different set of warnings is now being reported: `Warning:strict-aliasing`. Latest jobs continue to generate these same warnings.

There are no warnings for MacOS or Windows.

/cc @ros2/team is there someone who looked into the initial warnings or did they change as a side-effect of other updates?

**Comment by mikaelarguedas** [comment] 2017-10-25 15:50
Looks like the `Warning:unused-variable` warnings were a side effect of https://github.com/ros2/rosidl/pull/241
and have been fixed in https://github.com/ros2/rosidl/commit/52830d1e45ad3f3cb470dfd3fd093735a205ead1. 

For `Warning:strict-aliasing` my guess is that it is a side effect of https://github.com/ros2/rmw_connext/pull/257, though I cant reproduce them locally

**Comment by mikaelarguedas** [comment] 2017-10-25 15:59
Edit: I didnt have the last version of the code... The referenced PR is indeed responsible for the new warnings. See https://github.com/ros2/rmw_connext/pull/262 for a potential fix

**Closed as completed** 2017-10-25 17:24 UTC
