### ISSUE TITLE
Windows builds have ~70 test failures

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#235] opened 2019-08-28 23:51 UTC
Backtraces similar to:
```
Traceback (most recent call last):
   File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "C:\Python37\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "C:\Python37\lib\site-packages\pytest.py", line 101, in <module>
     raise SystemExit(pytest.main())
   File "C:\Python37\lib\site-packages\_pytest\config\__init__.py", line 58, in main
     config = _prepareconfig(args, plugins)
   File "C:\Python37\lib\site-packages\_pytest\config\__init__.py", line 208, in _prepareconfig
     pluginmanager=pluginmanager, args=args
   File "C:\Python37\lib\site-packages\pluggy\hooks.py", line 289, in __call__
     return self._hookexec(self, self.get_hookimpls(), kwargs)
   File "C:\Python37\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
     return self._inner_hookexec(hook, methods, kwargs)
   File "C:\Python37\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
   File "C:\Python37\lib\site-packages\pluggy\callers.py", line 203, in _multicall
     gen.send(outcome)
   File "C:\Python37\lib\site-packages\_pytest\helpconfig.py", line 89, in pytest_cmdline_parse
     config = outcome.get_result()
   File "C:\Python37\lib\site-packages\pluggy\callers.py", line 80, in get_result
     raise ex[1].with_traceback(ex[2])
   File "C:\Python37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
     res = hook_impl.function(*args)
   File "C:\Python37\lib\site-packages\_pytest\config\__init__.py", line 716, in pytest_cmdline_parse
     self.parse(args)
   File "C:\Python37\lib\site-packages\_pytest\config\__init__.py", line 924, in parse
     self._preparse(args, addopts=addopts)
   File "C:\Python37\lib\site-packages\_pytest\config\__init__.py", line 870, in _preparse
     self.pluginmanager.load_setuptools_entrypoints("pytest11")
   File "C:\Python37\lib\site-packages\pluggy\manager.py", line 292, in load_setuptools_entrypoints
     plugin = ep.load()
   File "C:\Python37\lib\site-packages\importlib_metadata\__init__.py", line 90, in load
     module = import_module(match.group('module'))
   File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "C:\Python37\lib\site-packages\_pytest\assertion\rewrite.py", line 140, in exec_module
     exec(co, module.__dict__)
   File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\launch_testing_ros\__init__.py", line 19, in <module>
     from .test_runner import LaunchTestRunner
   File "C:\Python37\lib\site-packages\_pytest\assertion\rewrite.py", line 140, in exec_module
     exec(co, module.__dict__)
   File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\launch_testing_ros\test_runner.py", line 18, in <module>
     import launch_ros
   File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\launch_ros\__init__.py", line 17, in <module>
     from . import actions
   File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\launch_ros\actions\__init__.py", line 17, in <module>
     from .composable_node_container import ComposableNodeContainer
   File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\launch_ros\actions\composable_node_container.py", line 26, in <module>
     from .node import Node
   File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\launch_ros\actions\node.py", line 50, in <module>
     from rclpy.validate_namespace import validate_namespace
   File "C:\J\workspace\nightly_win_deb\ws\src\ros2\rclpy\rclpy\rclpy\validate_namespace.py", line 16, in <module>
     from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
   File "C:\J\workspace\nightly_win_deb\ws\src\ros2\rclpy\rclpy\rclpy\impl\implementation_singleton.py", line 31, in <module>
     rclpy_implementation = _import('._rclpy')
   File "C:\J\workspace\nightly_win_deb\ws\src\ros2\rclpy\rclpy\rclpy\impl\__init__.py", line 21, in _import
     return importlib.import_module(name, package='rclpy')
   File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
 ModuleNotFoundError: No module named 'rclpy._rclpy'
```

**Comment by j-rivero** [comment] 2019-09-06 23:13
I found the same problem while inspecting the failures on icecube after system upgrade (under the scope of #234). Jenkins seems to display that problems started on [build 7906](https://ci.ros2.org/job/ci_windows/7906/#showFailuresLink). If I'm not wrong that build is mentioned here https://github.com/ros2/launch/pull/323#issuecomment-526668084.

Some of these kind of backtraces can be solved is you call `setup.bat` before running the test manually from the system.

**Comment by dirk-thomas** [comment] 2019-09-06 23:21
> Jenkins seems to display that problems started on build 7906.

You can't conclude that from the `ci_windows` job since each build is using a completely different set of parameters.

Only the nightly jobs which are triggered with the exact same parameters using the current state every night allow you to determine when the failing tests showed up first - which seems to be: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1290/testReport/ (which is 13! days ago).

The referenced `launch` PR you mentioned was only merged 7 days ago and therefore can't be responsible for the failures. It's CI build obviously shows the same failures since they were already present on `master` when that PR was tested.

Anyway this needs to be resolved asap - two weeks of such a significant regression simply isn't acceptable.

**Comment by ivanpauno** [comment] 2019-09-09 15:37
As commented in https://github.com/ros2/rclpy/pull/417 and https://github.com/ros2/rclpy/pull/420, the cause of the problem is https://github.com/ros2/launch_ros/pull/54.

**Comment by hidmic** [comment] 2019-09-09 18:49
@ivanpauno beat me to it. The result of the discussion in the first two PRs may reshape the solution to this problem. But if we doubt we'll reach to a conclusion there soon, I'll send a fix ASAP to deal with how things currently are.

**Comment by cottsay** [comment] 2019-09-09 20:34
Thanks, @hidmic. Please let me know if there is anything I can do to help move this forward.

**Comment by ivanpauno** [comment] 2019-09-25 12:38
Fixed by https://github.com/ros2/launch_ros/pull/69.

**Closed as completed by ivanpauno** 2019-09-25 12:38 UTC
Labels: bug
