### ISSUE TITLE
`apply_patch` sometimes fail when building `rmw_connext_cpp`

### ISSUE THREAD

**Issue by ivanpauno** [ros2/build_farmer#273] opened 2020-04-23 20:30 UTC
Some examples:

* https://ci.ros2.org/job/ci_windows/9801/consoleFull#console-section-181
* https://ci.ros2.org/job/ci_linux/10214/
* https://ci.ros2.org/job/ci_linux/10021/console#console-section-28
* https://ci.ros2.org/job/ci_linux/10451/console

There are much other cases.
I've seen this failure only on `Linux` and `Windows`.

It's extremely flaky and hard to reproduce.

**Comment by mjcarroll** [comment] 2020-04-24 19:43
https://ci.ros2.org/job/ci_linux/10501/console

**Comment by ivanpauno** [comment] 2020-04-24 20:49
Update:

In the successful builds, the generated `connext_static_serialized_dataPlugin.h` has these lines:

```
extern "C" {

```

In the ones that files, those lines are missing.
That makes `NDDSUSERDllExport extern struct PRESTypePlugin*` to be exactly in line `324` in successful builds, and in line `322` for the ones that fails.

Here's a diff of both files:

https://gist.github.com/ivanpauno/6edbfd73d522b677afcbb11794ecd075

**Comment by clalancette** [comment] 2020-04-24 21:11
Digging into the rti distribution code a bit, it looks like there is this bit in the template file:

```
#*--*##if(!${envMap.namespace} && $envMap.language.equals("Cpp"))
extern "C" {
#*--*##end
```

So in the failing case, either the "namespace" is being set, or the "language" is not "Cpp".  Not sure which case it is yet.

**Comment by dirk-thomas** [comment] 2020-04-24 21:24
We pass these options unconditionally: https://github.com/ros2/rosidl_typesupport_connext/blob/2a408f8f410c68c9b67ece28d245fcbaefbfc3d5/rosidl_typesupport_connext_cpp/rosidl_typesupport_connext_cpp/__init__.py#L57-L58

**Comment by clalancette** [comment] 2020-04-27 12:57
Well, where this actually occurred is in the earlier call to rtiddsgen_server, here: https://github.com/ros2/rmw_connext/blob/ba9c76b208da8f40ded4178a641766679baab26f/rmw_connext_cpp/CMakeLists.txt#L96 .  But yes, we pass the `-language C++` and no `-namespace` arguments there unconditionally, so we should *always* see `extern "C"` in the generated code.

At this point, I can only surmise that this is a race condition when starting up rtiddsgen_server; this is the very first time it is being run, so maybe something gets lost between the command-line and the server itself.  Hard to say since we don't have access to the code.

I think the workaround here is probably what you mentioned earlier, which is to look into the generated file and retry if it does *not* contain `extern "C"`.  This may or may not require restarting `rtiddsgen_server`, and since we don't have a reliable reproducer, we'll just have to try a couple of things and see what helps.

**Comment by clalancette** [comment] 2020-05-07 16:38
In all likelihood this was fixed by https://github.com/ros2/rmw_connext/pull/421 , so I'll close.  If it pops up again we can reopen.

**Closed as completed by clalancette** 2020-05-07 16:38 UTC
Labels: bug

**Comment by dirk-thomas** [comment] 2020-05-07 16:43
@clalancette Should ros2/rmw_connext#415 be reverted then?

**Comment by clalancette** [comment] 2020-05-07 16:46
I guess we can.  It likely isn't necessary, though it isn't hurting anything at the moment either.

**Comment by dirk-thomas** [comment] 2020-05-07 16:48
If there is no case where it is used / being helpful I would say revert it.

**Comment by dirk-thomas** [comment] 2020-05-18 16:54
@clalancette Friendly ping.

**Comment by clalancette** [comment] 2020-06-11 14:41
See https://github.com/ros2/rmw_connext/pull/425
