### ISSUE TITLE
Catastrophic test failures on nightly_linux_*

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#4] opened 2017-04-12 21:29 UTC
The nightly linux jobs for 11/12 April had a huge jump in failed tests.

- [linux_nightly_coverage](http://ci.ros2.org/view/nightly/job/nightly_linux_coverage/346/)
- [linux_nightly_debug](http://ci.ros2.org/view/nightly/job/nightly_linux_debug/419)
- [linux_nightly_release](http://ci.ros2.org/view/nightly/job/nightly_linux_release/409/)
- [linux_nightly_repeated](http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/617/)

Two things happened yesterday before these jobs ran which may point to the failures:

1. A PR to rmw_fastrtps designed to work against Fast-RTPS master (but tested briefly on our targeted revision) https://github.com/ros2/rmw_fastrtps/pull/101
2. A Jenkins upgrade that altered plugin configuration

While arbitrarily sampling tests I came across an out of memory error in [test_publisher_subscriber__BoundedArrayPrimitives__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp](http://ci.ros2.org/view/nightly/job/nightly_linux_debug/419/testReport/junit/projectroot/rosidl_generator_py/test_publisher_subscriber__BoundedArrayPrimitives__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp/)

```
Traceback (most recent call last):
  File "/home/rosbuild/ci_scripts/venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/rosbuild/ci_scripts/ws/build/test_communication/test_publisher_subscriber__BoundedArrayPrimitives__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp_Debug.py", line 43, in test_publisher_subscriber
    "The launch file failed with exit code '" + str(rc) + "'. " \
AssertionError: The launch file failed with exit code '-6'. May be the subscriber did not receive any messages?
-------------------- >> begin captured stdout << ---------------------
(test_publisher) pid 23105: ['/home/rosbuild/ci_scripts/venv/bin/python3', '/home/rosbuild/ci_scripts/ws/src/ros2/system_tests/test_communication/test/publisher_py.py', 'BoundedArrayPrimitives'] (stderr > stdout, all > console)
(test_subscriber) pid 23106: ['/home/rosbuild/ci_scripts/venv/bin/python3', '/home/rosbuild/ci_scripts/ws/src/ros2/system_tests/test_communication/test/subscriber_py.py', 'BoundedArrayPrimitives'] (stderr > stdout, all > console)
[test_subscriber] terminate called after throwing an instance of 'eprosima::fastcdr::exception::NotEnoughMemoryException'
[test_subscriber]   what():  Not enough memory in the buffer stream
(test_subscriber) rc -6
() tear down
```

cc @wjwwood who wanted a link to this issue.

**Comment by wjwwood** [comment] 2017-04-12 21:33
Thanks, I'm going to look into it more detail asap.

**Comment by mikaelarguedas** [comment] 2017-04-12 21:41
FYI: I launched a round of CI since https://github.com/ros2/ros2/pull/332 has been merged to see if tracking Fast-RTPS fixes the issue
* Linux  [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2448)](http://ci.ros2.org/job/ci_linux/2448/)
* MacOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1894)](http://ci.ros2.org/job/ci_osx/1894/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2567)](http://ci.ros2.org/job/ci_windows/2567/)
* Linux aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=73)](http://ci.ros2.org/job/ci_linux-aarch64/73/)

**Comment by wjwwood** [comment] 2017-04-12 22:00
Thanks @mikaelarguedas I'll wait for those to see if it addresses the issue.

**Comment by wjwwood** [comment] 2017-04-12 22:30
@mikaelarguedas it's looking good, the macOS and Windows jobs are yellow due to existing issues.

**Comment by mikaelarguedas** [comment] 2017-04-12 22:30
Confirmed: https://github.com/ros2/rmw_fastrtps/pull/101 is the culprit and all tests passed (on the first run!) on http://ci.ros2.org/job/ci_linux/2448/ so I think it's safe to not investigate the last nightlies failures if the other jobs come back green too

**Comment by nuclearsandwich** [comment] 2017-04-12 22:32
> so I think it's safe to not investigate the last nightlies failures if the other jobs come back green too

phew! 😰

**Comment by wjwwood** [comment] 2017-04-12 22:35
🎉 @nuclearsandwich I'll let you close it 😄 once the CI jobs finish completely.

**Comment by nuclearsandwich** [comment] 2017-04-13 12:30
The Linux builds are green and the MacOS and Windows builds have a few warnings but the tests all pass so I am indeed closing this.

I am somewhat curious why this came up when our manual CI job http://ci.ros2.org/job/ci_linux/2428/ had no issues at all. But not curious enough to prioritize digging into it above other work.

**Comment by mikaelarguedas** [comment] 2017-04-13 12:35
Me neither, I had failures locally but because I don't "retest until pass" I thought it was normal and that it was only due to flakiness. Agreed it's not work investigating

**Closed as completed** 2017-04-13 12:37 UTC
