### ISSUE TITLE
Error generating repository hashes causing most jobs to fail

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#24] opened 2017-05-28 17:36 UTC
Not looking into this just yet but I definitely got the emails and am going to when I have the time.

**Comment by dirk-thomas** [comment] 2017-05-29 18:16
The issue doesn't contain enough information for a reader to understand what the problem is. A link to a failing job as well as a snippet of the command failing with the actual error message would be helpful.

**Comment by dirk-thomas** [comment] 2017-05-29 18:39
Fixed by dirk-thomas/vcstool#42

**Closed as completed by dirk-thomas** 2017-05-29 18:39 UTC

**Comment by nuclearsandwich** [comment] 2017-05-29 19:59
> The issue doesn't contain enough information for a reader to understand what the problem is. A link to a failing job as well as a snippet of the command failing with the actual error message would be helpful.

I understand the feedback, this was really just an acknowledgement that as the build {farmer,cop} I've seen the failures. I wasn't expecting anyone else to look into it on a holiday weekend and was just coming to them myself when I saw that you resolved it.. Which.. thanks!
