### ISSUE TITLE
Nightly jobs come back green even if they have test failures

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#120] opened 2018-05-29 17:02 UTC
I noticed this in the last nightlies but it seems that's been happening for a while:
https://ci.ros2.org/view/nightly/job/nightly_linux_debug/846/consoleFull#console-section-518

`Summary: 17110 tests, 0 errors, 5 failures, 19 skipped` but the job is green

Looks like the linux jobs started failing on https://ci.ros2.org/view/nightly/job/nightly_linux_debug/838/

**Comment by dhood** [comment] 2018-05-29 17:06
maybe just the "pure" pytest failures don't get picked up

**Comment by dirk-thomas** [comment] 2018-05-30 19:50
All "missed" test results are of the form `build/<pkgname>/pytest.xml`. The configured paths for the Jenkins plugin extracting the warnings simply don't match these paths.

**Comment by dirk-thomas** [comment] 2018-05-30 20:38
Some of the test failures have been addressed by the referenced PRs. The remaining ones are due to a regression in the latest Pyflakes release 2.0.0 (see PyCQA/pyflakes#333). Hopefully upstream will be able to resolve this quickly and we don't have to add `noqa` ignores to these lines.

**Closed as completed** 2018-05-31 16:22 UTC
Labels: bug, in review
